# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema: "*.graphql"
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver

models:
  Todo:    # Object
    fields:
      id:
        resolver: true
      text:
        fieldName: Description # Field
  NewTodo: # Input
    fields:
      userId:
        fieldName: UserID      # Field
  User:
    model: github.com/99designs/gqlgen/example/config.User
    fields:
      name:
        fieldName: FullName    # Method
