version: 2
jobs:
  build:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/vektah/gqlgen
    steps: &steps
      - checkout
      - run: >
          curl -L -o /bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 &&
          chmod +x /bin/dep &&
          go get -u github.com/alecthomas/gometalinter github.com/vektah/gorunpkg &&
          gometalinter --install &&
          dep ensure --vendor-only
      - run: go install -v . && go get -u github.com/vektah/dataloaden
      - run: go generate ./... && if [[ $(git diff) ]] ; then echo "you need to run go generate" ; git diff ; exit 1 ; fi
      - run: go vet ./...
      - run: go test -race ./...
      - run: gometalinter --disable gocyclo ./example
