baseurl: https://gqlgen.com/
metadataformat: yaml
title: gqlgen
enableGitInfo: true
pygmentsCodeFences: true
pygmentsUseClasses: true
canonifyURLs: true

params:
  name: gqlgen
  description: graphql servers the easy way

menu:
  main:
    - name: Introduction
      url: /
      weight: -10
    - name: Reference
      identifier: reference
      weight: 5
    - name: Recipes
      identifier: recipes
      weight: 10
