name: Security
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize]
env:
  GOTOOLCHAIN: "local"
# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check-secret:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    outputs:
      my-secret-exists: ${{ steps.my-secret-check.outputs.defined }}
    steps:
    - name: Check for Secret availability
      id: my-secret-check
        # perform secret check and write boolean as output
      shell: bash
      run: |
          if [ "${{ secrets.OSSI_TOKEN }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  nancy: # only run when not in fork and secret is available
    runs-on: ubuntu-latest
    needs: [check-secret]
    if: needs.check-secret.outputs.my-secret-exists == 'true'
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        go: ["1.25"] # nancy is a little flaky running more than once
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
      with:
        persist-credentials: "false"
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: ${{ matrix.go }}
    - run: go mod download && go list -json -deps all > go.list
    - uses: sonatype-nexus-community/nancy-github-action@395e2fb168f674f96502e5652103d112899ea369 # main
      env:
        OSSI_USERNAME: "${{ secrets.OSSI_USERNAME }}"
        OSSI_TOKEN: "${{ secrets.OSSI_TOKEN }}"
